pipeline {
    agent any
    
    environment {
        // Define the path to chromedriver as an environment variable
        CHROMEDRIVER_PATH = '/usr/bin/chromedriver'
        VENV_PATH = '/home/student50/selenium_test/venv'
    }
    
    stages {
        stage('Clean Up') {
            steps {
                echo "Cleaning up..."
                sh 'docker compose down webapp'
                sh 'docker image prune -f --filter "dangling=true"'
            }
        }
        stage('Build') {
            steps {
                echo 'Building...'
                sh 'docker compose build webapp'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing...'
                dependencyCheck additionalArguments: ''' 
                    -o './'
                    -s './'
                    -f 'ALL' 
                    --prettyPrint''', odcInstallation: 'OWASP Dependency-Check Vulnerabilities'
        
                dependencyCheckPublisher pattern: 'dependency-check-report.xml'
            }
        }
        stage('Prepare Environment') {
            steps {
                echo 'Preparing Python virtual environment...'
                script {
                    // Check if the virtual environment directory exists
                    if (!fileExists("${VENV_PATH}/bin/activate")) {
                        // Recreate the virtual environment
                        sh "python3 -m venv ${VENV_PATH}"
                    }
                }
            }
        }
        stage('Selenium UI Test') {
            steps {
                echo 'Running Selenium Tests...'
                script {
                    // Use the full path to Bash and activate the virtual environment
                    sh '/bin/bash -c "source ${VENV_PATH}/bin/activate && CHROMEDRIVER_PATH=${CHROMEDRIVER_PATH} python /home/student50/selenium_test/login_test.py"'
                }
            }
        }

        
        
        stage('Deploy') {
            steps {
                echo 'Deploying...'
                sh 'docker compose up webapp -d'
                sh 'docker exec webapp cp /env/.env /app'
                sh 'docker exec webapp yarn prisma db push'
            }
        }
    }
}
