pipeline {
    agent any
    
    stages {
        stage('Clean Up') {
            steps {
                echo "Cleaning up..."
                sh 'docker compose down webapp'
                sh 'docker image prune -f --filter "dangling=true"'
            }
        }
        
        stage('Unit Test') {
            steps {
                echo 'Building test...'
                sh 'docker build --build-arg="ENV_VALUE=DEV" -t webapp-test .'
                echo 'Running test...'
                sh 'docker run --rm --name webapp-test -t webapp-test'
                sh 'docker rmi webapp-test'
            }
        }

        stage('Build') {
            steps {
                echo 'Building...'
                sh 'docker compose build webapp'
            }
        }
        
        stage('Test') {
            steps {
                echo 'Testing...'
                dependencyCheck additionalArguments: ''' 
                    -o './'
                    -s './'
                    -f 'ALL' 
                    --prettyPrint''', odcInstallation: 'OWASP Dependency-Check Vulnerabilities'
        
                dependencyCheckPublisher pattern: 'dependency-check-report.xml'
            }
        }
          
        stage('Deploy') {
            steps {
                echo 'Deploying...'
                sh 'docker compose up webapp -d'
                sh 'docker exec webapp cp /env/.env /app'
                sh 'docker exec webapp yarn prisma db push'
            }
        }
    }
}
